FROM nginx 
#:1.10.1-alpine
RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
#COPY content /usr/share/nginx/html
COPY index.html /usr/share/nginx/html
COPY conf /etc/nginx
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
